apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-aws-auth
  namespace: default
spec:
  secretTargetRef:
    - parameter: awsAccessKeyID
      name: aws
      key: AWS_ACCESS_KEY_ID
    - parameter: awsSecretAccessKey
      name: aws
      key: AWS_SECRET_ACCESS_KEY
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: sqs-scaledjob
  namespace: default
spec:
  jobTargetRef:
    template:
      spec:
        containers:
        - name: sqs-job-processor
          image: mhsource/nodes:v4
          env:
          - name: AWS_REGION
            value: us-east-2
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws
                key: AWS_SECRET_ACCESS_KEY
          - name: SQS_QUEUE_URL
            value: https://sqs.us-east-2.amazonaws.com/108782070139/ok
        restartPolicy: OnFailure
  pollingInterval: 30
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  maxReplicaCount: 10
  triggers:
  - type: aws-sqs-queue
    metadata:
      queueURL: https://sqs.us-east-2.amazonaws.com/108782070139/ok
      queueLength: "5"
      awsRegion: "us-east-2"
    authenticationRef:
      name: keda-aws-auth
